language: python
python:
  - "3.7"
  - "3.9"
# command to install dependencies
cache: pip
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install mypy
# command to run tests
script:
  - mypy --ignore-missing-imports camfi.py
  - python -m doctest camfi.py
