language: python
python:
  - "3.9"
# command to install dependencies
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - pip install .
  - pip install pytest-cov pytest-mypy
# Setting environment variables
env:
  - SKYFIELD_DATA_DIR="camfi/test/data" CAMFI_EPHEMERIS="test_ephem.bsp"
# command to run tests
script:
  - pytest
