language: python
python:
  - "3.7"
# command to install dependencies
cache: pip
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install pytest-cov pytest-mypy
# command to run tests
script:
  - pytest
